services:
  db:
    container_name: db
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_DB_PWD}

  s3-service:
    container_name: s3
    image: public.ecr.aws/aws-cli/aws-cli
    environment:
      - AWS_ACCESS_KEY_ID=${ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${REGION}
    volumes:
      - 'db_data:/backup'
    command: s3 sync --endpoint-url=${S3_ENDPOINT} /backup s3://${BUCKET_NAME}
volumes:
  db_data: