services:

  db:
    container_name: db
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_DB_PWD}

  s3sync-service:
    image: ghcr.io/mazay/s3sync-service:master
    environment:
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - BUCKET_REGION=${BUCKET_REGION}
    volumes:
      - '/backup:/backup'
      - './config/backup.yml:/app/config.yml'

volumes:
  db_data: